stepshop/authapp/urls.py
from django.urls import path

from authapp.views import login, register, logout, edit

app_name = 'auth'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('logout/', logout, name='logout'),

]

stepshop/cart/urls.py
from django.urls import path

from cart.views import cart, cart_add, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart, name='view'),
    path('add/<int:pk>/', cart_add, name='add'),
    path('remove/<int:pk>/', cart_remove, name='remove'),
]

stepshop/products/urls.py
from django.urls import path
from products.views import products, product

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path('product/<int:pk>/', product, name='product'),
]

stepshop/stepshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from stepshop.views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('products.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('cart/', include('cart.urls', namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/products/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    def __str__(self):
        return self.name or f'Категория с id - {self.pk}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='подкатегория',
    )

    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )

    image = models.ImageField(
        upload_to='product_images',
        blank=True,
        verbose_name='изображение',
    )

    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=128,
        blank=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )

    quantity = models.PositiveIntegerField(
        verbose_name='количество товара на складе',
        default=0,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name or f'Продукт с id - {self.pk}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

stepshop/products/views.py
from django.shortcuts import render, get_object_or_404

from cart.models import Cart
from products.models import Product, ProductCategory

links_menu = [
    {'href': 'index', 'name': 'Главная', 'route': ''},
    {'href': 'products:index', 'name': 'Продукты', 'route': 'products/'},
    {'href': 'about', 'name': 'О&nbsp;нас', 'route': 'about/'},
    {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
]


def get_cart(user):
    if user.is_authenticated:
        return Cart.objects.filter(user=user)
    return []


def get_same_products(current_product):
    return Product.objects.filter(category=current_product.category).exclude(pk=current_product.pk)


def products(request, pk=None):
    title = 'Продукты'

    products_ = Product.objects.all()
    # products_ = Product.objects.all().filter(category__name__in=['Джинсы', 'Кеды']).order_by('price')
    # products_ = Product.objects.all().filter(category__name='Джинсы', price__lt=600) - фильтр по имени товара
    # products_ = Product.objects.all().filter(category__name__endswith='ы') - товар кончается на "ы"
    # products_ = Product.objects.all().exclude(category__name__startswith='Д') - исключи
    # products_ = Product.objects.all().get(startswith='Д')
    categories = ProductCategory.objects.all()

    cart = []

    if request.user.is_authenticated:
        cart = Cart.objects.filter(user=request.user)

    if pk is not None:
        if pk == 0:
            products_ = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products_ = Product.objects.filter(category__pk=pk).order_by('price')

        context = {
            'title': title,
            'links_menu': links_menu,
            'products': products_,
            'categories': categories,
            'category': category,
            'cart': cart,
        }
        return render(request, 'products.html', context)

    context = {
        'title': title,
        'links_menu': links_menu,
        'products': products_,
        'categories': categories,
        'cart': cart,
    }

    return render(request, 'products.html', context)


def product(request, pk):
    title = 'Продукт'

    context = {
        'title': title,
        'links_menu': links_menu,
        'product': get_object_or_404(Product, pk=pk),
        'cart': get_cart(request.user),
        'same_products': get_same_products(get_object_or_404(Product, pk=pk)),
    }

    return render(request, 'product.html', context)

stepshop/stepshop/views.py
from django.shortcuts import render

links_menu = [
    {'href': 'index', 'name': 'Главная', 'route': ''},
    {'href': 'products:index', 'name': 'продукты', 'route': 'products/'},
    {'href': 'about', 'name': 'О&nbsp;нас', 'route': 'about/'},
    {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
    # {'href': 'cart', 'name': 'корзина', 'route': 'cart/'}, -- не работает
]


def index(request):
    title = 'Главная страница'

    context = {
        'title': title,
        'links_menu': links_menu
    }

    return render(request, 'index.html', context)
    # return render(request=request, template_name='index.html', context=context)


def about(request):
    title = 'О нас'
    context = {
        'title': title,
        'links_menu': links_menu,
    }
    return render(request, 'about.html', context)


def contacts(request):
    title = 'Контакты'
    context = {
        'title': title,
        'links_menu': links_menu
    }
    return render(request, 'contact.html', context)


def cart(request):
    title = 'Корзина'
    context = {
        'title': title,
        'links_menu': links_menu
    }
    return render(request, 'cart.html', context)

stepshop/stepshop/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ title|capfirst }}
{% endblock %}

{% block content %}

    <!-- Page Content -->
    <!-- About Page Starts Here -->
    <div class="about-page">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Кто мы такие</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-image">
              <img src="{% static 'assets/images/about-us.jpg' %}" alt="people">
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <h4>Наш супер магазин основан:</h4>
              <p>Goes to Pexels website. Aliquam erat volutpat. Pellentesque fringilla, ligula consectetur cursus scelerisque, leo elit pellentesque sapien, et pharetra arcu elit vitae sem. Suspendisse erat dui, condimentum in mi ac, varius tempor sapien. Donec in justo sit amet ex aliquet maximus ac quis erat.</p>
              <br>
              <p>Donec fermentum tincidunt tellus quis fermentum. Proin eget imperdiet purus. Nulla facilisi. Aliquam tincidunt porttitor dui sed euismod. Duis est libero, rhoncus fermentum turpis id, tempus fringilla ipsum. Nullam venenatis tincidunt neque vel hendrerit. Suspendisse porta pretium porttitor.</p>
              <br>
              <p>Sed purus quam, ultricies eu leo in, sollicitudin varius quam. Proin dictum urna ac diam fermentum tempus. Pellentesque urna urna, ullamcorper a tincidunt dignissim, venenatis in nisi. Vivamus in volutpat tellus. Etiam fermentum luctus posuere.</p>
              <br>
              <p>Pixie HTML Template can be converted into your desired CMS theme. You can use this Bootstrap v4.1.3 layout for any online shop. Please tell your friends about. Thank you.</p>
              <div class="share">
                <h6>Ищите нас в соцсетях: <span><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-twitter"></i></a></span></h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- About Page Ends Here -->
{% endblock %}

stepshop/stepshop/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">
    <title>{% block title %}PageName{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">-->
    <!--    <link href="/static/stepshop/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/tooplate-main.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css'%}">
    {% block css %}{% endblock %}

</head>

<body>

<!-- Pre Header -->
<div id="pre-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12 d-flex justify-content-end align-items-center text-light">

                {% if user.is_authenticated %}
                {% if user.is_superuser %}
                <a href="/admin/" class="nav-link">
                    <span>Админка</span>
                </a>
                |
                {% endif %}

                <a href="{% url 'auth:edit' %}" class="nav-link">
                    <span>{{ user.first_name|default:'Пользователь' }}</span>
                </a>
                |
                <a href="{% url 'auth:logout' %}" class="nav-link">
                    <span>Выйти</span>
                </a>
                {% else %}
                <a href="{% url 'auth:login' %}" class="nav-link">
                    <span>Войти</span>
                </a>
                {% endif %}
                {% if cart %}
                <a href="{% url 'cart:view' %}" class="cart">
                    <span>{{ cart.0.total_quantity }}</span>
                </a>
                |
                <div class="nav-link">$ {{ cart.0.total_cost|floatformat:'g' }}</div>
                {% endif %}

            </div>
        </div>
    </div>
</div>

{% include 'includes/inc_main_menu.html' %}

{% block content %}
HTML
{% endblock %}



<!-- Sub Footer Starts Here -->
<div class="sub-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="copyright-text">
                    <p>Copyright &copy; 2019&ndash;{% now "Y" %} Company Name

                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Sub Footer Ends Here -->


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>


<!-- Additional Scripts -->
<script src="{% static 'assets/js/custom.js'%}"></script>
<script src="{% static 'assets/js/owl.js'%}"></script>

{% block js %}{% endblock %}

<script language="text/Javascript">
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }



</script>


</body>

</html>

stepshop/stepshop/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ title|capfirst }}
{% endblock %}

{% block content %}

    <!-- Page Content -->
    <!-- About Page Starts Here -->
    <div class="contact-page">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Контакты:</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div id="map">
            		<!-- How to change your own map point
                           1. Go to Google Maps
                           2. Click on your location point
                           3. Click "Share" and choose "Embed map" tab
                           4. Copy only URL and paste it within the src="" field below
                    -->
              <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d2906.5681993510484!2d76.90491435609741!3d43.23951212438764!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2skz!4v1654681446947!5m2!1sru!2skz" width="550" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <div class="container">
                <form id="contact" action="" method="post">
                  <div class="row">
                    <div class="col-md-6">
                      <fieldset>
                        <input name="name" type="text" class="form-control" id="name" placeholder="Ваше имя..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-6">
                      <fieldset>
                        <input name="email" type="text" class="form-control" id="email" placeholder="Ваш email..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <input name="subject" type="text" class="form-control" id="subject" placeholder="Тема..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <textarea name="message" rows="6" class="form-control" id="message" placeholder="Ваше сообщение..." required=""></textarea>
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <button type="submit" id="form-submit" class="button">Отправить сообщение</button>
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <div class="share">
                        <h6>Также следите за нами в соцсетях: <span><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-twitter"></i></a></span></h6>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- About Page Ends Here -->
{% endblock %}

stepshop/stepshop/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

<title>{% block title %}{{title|capfirst}}{% endblock %}</title>

{% block content %}

<!-- Page Content -->
<!-- Banner Starts Here -->
<div class="banner">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="caption">
                    <h2>Наш HTML проект Django</h2>
                    <div class="line-dec"></div>
                    <p>Это наш HTML шаблон для работы в проекте Django на нашем курсе по Python.
                        <br><br>Пожалуйста никому не рассказывайте о нем на
                        сайте. Спасибо.
                    <div class="main-button">
                        <a href="#">Не заказывайте!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Ends Here -->

<!-- Featured Starts Here -->
<div class="featured-items">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-heading">
                    <div class="line-dec"></div>
                    <h1>Товары для Вас!</h1>
                </div>
            </div>
            <div class="col-md-12">
                <div class="owl-carousel owl-theme">
                    <a href="single-product.html">
                        <div class="featured-item">
                    <img src="{{ product.image|media_folder_products }}" alt="{{ product.name }}">
                    <h4>{{ product.name }}</h4>
                    <h6>{{ product.name }}</h6>
                </div>
                    </a>
                    <a href="single-product.html">
                        <div class="featured-item">
                            <img src="{% static 'assets/images/item-02.jpg'%}" alt="Item 2">
                            <h4>Erat odio rhoncus</h4>
                            <h6>$25.00</h6>
                        </div>
                    </a>
                    <a href="single-product.html">
                        <div class="featured-item">
                            <img src="{% static 'assets/images/item-03.jpg'%}" alt="Item 3">
                            <h4>Integer vel turpis</h4>
                            <h6>$35.00</h6>
                        </div>
                    </a>
                    <a href="single-product.html">
                        <div class="featured-item">
                            <img src="{% static 'assets/images/item-04.jpg'}" alt="Item 4">
                            <h4>Sed purus quam</h4>
                            <h6>$45.00</h6>
                        </div>
                    </a>
                    <a href="single-product.html">
                        <div class="featured-item">
                            <img src="{% static 'assets/images/item-05.jpg'%}" alt="Item 5">
                            <h4>Morbi aliquet</h4>
                            <h6>$55.00</h6>
                        </div>
                    </a>
                    <a href="single-product.html">
                        <div class="featured-item">
                            <img src="{% static 'assets/images/item-06.jpg'%}" alt="Item 6">
                            <h4>Urna ac diam</h4>
                            <h6>$65.00</h6>
                        </div>
                    </a>
                    <a href="single-product.html">
                        <div class="featured-item">
                            <img src="{% static 'assets/images/item-04.jpg'%}" alt="Item 7">
                            <h4>Proin eget imperdiet</h4>
                            <h6>$75.00</h6>
                        </div>
                    </a>
                    <a href="single-product.html">
                        <div class="featured-item">
                            <img src="{% static 'assets/images/item-05.jpg'%}" alt="Item 8">
                            <h4>Nullam risus nisl</h4>
                            <h6>$85.00</h6>
                        </div>
                    </a>
                    <a href="single-product.html">
                        <div class="featured-item">
                            <img src="{% static 'assets/images/item-06.jpg'%}" alt="Item 9">
                            <h4>Cras tempus</h4>
                            <h6>$95.00</h6>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Featred Ends Here -->
{% endblock %}

stepshop/stepshop/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ title|capfirst }}
{% endblock %}

{% block content %}

    <!-- Page Content -->
    <!-- Single Starts Here -->
    <div class="single-product">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>{{ product.name }}</h1>
            </div>
          </div>
          <div class="col-md-6">
            <img src="/media/{{ product.image }}" alt="{{ product.name }}" class="w-100"/>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <h4>{{ product.name }}</h4>
              <h6>{{ product.price|floatformat:'g' }} тенге</h6>
              <p>{{ product.description }}</p>
              <span>На складе {{ product.quantity}} шт.</span>

              <button type="button" class="button">
                <a href="{% url 'cart:add' product.pk %}" class="text-light">В корзину</a>
              </button>

              <div class="down-content">
                <div class="categories">
                  <h6>Категория: <span><a href="{% url 'products:category' product.category.id %}">{{ product.category }}</a></span></h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Single Page Ends Here -->


    <!-- Similar Starts Here -->
    {% if same_products %}
    <div class="featured-items">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Вам может также понравиться:</h1>
            </div>
          </div>
          <div class="col-md-12">
            <div class="owl-carousel owl-theme">

              {% for product in same_products %}
              <a href="{% url 'products:product' product.pk %}">
                <div class="featured-item">
                  <img src="/media/{{ product.image }}" alt="{{ product.name }}">
                  <h4>{{ product.name }}</h4>
                  <h6>{{ product.price|floatformat:'g' }} тенге</h6>
                </div>
              </a>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
    <!-- Similar Ends Here -->

{% endblock %}

stepshop/stepshop/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
{{ title|capfirst }}
{% endblock %}

{% block content %}

<!-- Page Content -->
<!-- Items Starts Here -->
{% include 'includes/inc_category_menu.html' %}

<div class="featured container no-gutter">

    <div class="row posts">

        {% for product in products %}
        <div id="{{ product.pk }}" class="item new col-md-4">
            <a href="{% url 'products:product' product.pk %}">
                <div class="featured-item">
                    <img src="{{ product.image|media_folder_products }}" alt="{{ product.name }}">
                    <h4>{{ product.name }}</h4>
                    <h6>{{ product.name }}</h6>
                </div>
            </a>
        </div>

        {% endfor %}

    </div>
</div>

<!--<div class="page-navigation">-->
<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            <div class="col-md-12">-->
<!--                <ul>-->
<!--                    <li class="current-page"><a href="#">1</a></li>-->
<!--                    <li><a href="#">2</a></li>-->
<!--                    <li><a href="#">3</a></li>-->
<!--                    <li><a href="#"><i class="fa fa-angle-right"></i></a></li>-->
<!--                </ul>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<!-- Featred Page Ends Here -->

{% endblock %}

{% block js %}
    <script src="{% static 'assets/js/isotope.js'%}"></script>
{% endblock %}