stepshop/cart/urls.py
from django.urls import path

from cart.views import cart, cart_add, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart, name='view'),
    path('add/<int:pk>/', cart_add, name='add'),
    path('remove/<int:pk>/', cart_remove, name='remove'),
]

stepshop/stepshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from stepshop.views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('products.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('cart/', include('cart.urls', namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/cart/models.py
from django.db import models

from products.models import Product
from stepshop import settings


class Cart(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='cart',
    )

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
    )

    quantity = models.PositiveIntegerField(
        verbose_name='количество',
        default=0,
    )

    add_datetime = models.DateTimeField(
        verbose_name='время',
        auto_now_add=True,
    )

    @property
    def product_cost(self):
        return self.product.price * self.quantity

    @property
    def total_quantity(self):
        _items = Cart.objects.filter(user=self.user)
        _total_quantity = sum(list(map(lambda x: x.quantity, _items)))
        return _total_quantity

    @property
    def total_cost(self):
        _items = Cart.objects.filter(user=self.user)
        _total_cost = sum(list(map(lambda x: x.product_cost, _items)))
        return _total_cost

stepshop/cart/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponseRedirect
from django.urls import reverse

from cart.models import Cart
from products.models import Product

links_menu = [
    {'href': 'index', 'name': 'Главная', 'route': ''},
    {'href': 'products:index', 'name': 'Продукты', 'route': 'products/'},
    {'href': 'about', 'name': 'О&nbsp;нас', 'route': 'about/'},
    {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
]


@login_required
def cart(request):
    if request.user.is_authenticated:
        cart_ = Cart.objects.filter(user=request.user)
        context = {
            'cart': cart_,
            'links_menu': links_menu,
        }

        return render(request, 'cart/cart.html', context)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def cart_add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:product', args=[pk]))

    product = get_object_or_404(Product, pk=pk)

    cart_ = Cart.objects.filter(user=request.user, product=product).first()

    if not cart_:
        cart_ = Cart(user=request.user, product=product)

    cart_.quantity += 1
    cart_.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def cart_remove(request, pk):
    cart_record = get_object_or_404(Cart, pk=pk)
    cart_record.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

stepshop/stepshop/views.py
from django.shortcuts import render

links_menu = [
    {'href': 'index', 'name': 'Главная', 'route': ''},
    {'href': 'products:index', 'name': 'продукты', 'route': 'products/'},
    {'href': 'about', 'name': 'О&nbsp;нас', 'route': 'about/'},
    {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
    # {'href': 'cart', 'name': 'корзина', 'route': 'cart/'}, -- не работает
]


def index(request):
    title = 'Главная страница'

    context = {
        'title': title,
        'links_menu': links_menu
    }

    return render(request, 'index.html', context)
    # return render(request=request, template_name='index.html', context=context)


def about(request):
    title = 'О нас'
    context = {
        'title': title,
        'links_menu': links_menu,
    }
    return render(request, 'about.html', context)


def contacts(request):
    title = 'Контакты'
    context = {
        'title': title,
        'links_menu': links_menu
    }
    return render(request, 'contact.html', context)


def cart(request):
    title = 'Корзина'
    context = {
        'title': title,
        'links_menu': links_menu
    }
    return render(request, 'cart.html', context)

stepshop/stepshop/templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
{{ title|capfirst }}
{% endblock %}


{% block content %}
{% if user.is_authenticated %}

<div class="container w-50 mt-5">
    <div class="row cart-list">
        <table class="table mt-3">
            <thead>
            <tr>
                <th class="col-1">№</th>
                <th class="col">Продукт</th>
                <th class="col">Количество</th>
                <th class="col">Стоимость</th>
                <th class="col">Удалить</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.product }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.product.price }}</td>
                <td>
                    <button class="btn btn-round">
                        <a href="{% url 'cart:remove' item.pk %}">Удалить</a>
                    </button>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    <div class="justify-content-end">
        Всего товаров: <strong>{{ cart.0.total_quantity }}</strong>
        <br>
        На сумму:  <strong> $ {{ cart.0.total_cost|floatformat:'g' }}</strong>
    </div>
</div>
{% endif %}
{% endblock %}