stepshop/authapp/urls.py
from django.urls import path

from authapp.views import login, register, logout, edit

app_name = 'auth'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('logout/', logout, name='logout'),

]

stepshop/cart/urls.py
from django.urls import path

from cart.views import cart, cart_add, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart, name='view'),
    path('add/<int:pk>/', cart_add, name='add'),
    path('remove/<int:pk>/', cart_remove, name='remove'),
]

stepshop/stepshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from stepshop.views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('products.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('cart/', include('cart.urls', namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class ShopUser(AbstractUser):
    avatar = models.ImageField(
        upload_to='users_avatars',
        blank=True,
        verbose_name='Аватарка',
    )

    age = models.PositiveIntegerField(
        verbose_name='возраст',

    )

stepshop/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator

from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = {'username', 'password'}

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ShopUserRegisterForm(UserCreationForm):
    username = forms.CharField(
        max_length=128,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Логин...',
                'id': 'login',
            }
        )
    )
    first_name = forms.CharField(
        max_length=64,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Имя...',
                'id': 'name',
            }
        )
    )

    password1 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'id': 'password1',
            }
        )
    )

    password2 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'id': 'password2',
            }
        )
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Введите email...',
                'id': 'email',
            }
        )
    )

    age = forms.IntegerField(
        validators=[MaxValueValidator(100),
                    MinValueValidator(0)],
        widget=forms.NumberInput(
            attrs={
                'placeholder': 'Возраст...',
                'id': 'age',
                'min': 0,
                'max': 100,
            }
        )
    )

    class Meta:
        model = ShopUser
        fields = {'username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']

        if data < 18:
            raise forms.ValidationError('Вы слишком молоды...')

        return data


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = {'username', 'first_name', 'email', 'age', 'avatar', 'password'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']

        if data < 18:
            raise forms.ValidationError('Вы слишком молоды...')

        return data

stepshop/authapp/views.py
from django.contrib import auth
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm


def login(request):
    title = 'Вход'

    login_form = ShopUserLoginForm(data=request.POST)

    _next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user and user.is_active:
            auth.login(request, user)

            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])

            return HttpResponseRedirect(reverse('index'))

    context = {
        'title': title,
        'login_form': login_form,
        'next': _next,
    }

    return render(request, 'authapp/login.html', context)


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))

    else:
        register_form = ShopUserRegisterForm()

    context = {
        'title': title,
        'register_form': register_form,
    }

    return render(request, 'authapp/register.html', context)


def edit(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))

    else:
        edit_form = ShopUserEditForm(instance=request.user)

    context = {
        'title': title,
        'edit_form': edit_form,
    }

    return render(request, 'authapp/edit.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

stepshop/stepshop/views.py
from django.shortcuts import render

links_menu = [
    {'href': 'index', 'name': 'Главная', 'route': ''},
    {'href': 'products:index', 'name': 'продукты', 'route': 'products/'},
    {'href': 'about', 'name': 'О&nbsp;нас', 'route': 'about/'},
    {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
    # {'href': 'cart', 'name': 'корзина', 'route': 'cart/'}, -- не работает
]


def index(request):
    title = 'Главная страница'

    context = {
        'title': title,
        'links_menu': links_menu
    }

    return render(request, 'index.html', context)
    # return render(request=request, template_name='index.html', context=context)


def about(request):
    title = 'О нас'
    context = {
        'title': title,
        'links_menu': links_menu,
    }
    return render(request, 'about.html', context)


def contacts(request):
    title = 'Контакты'
    context = {
        'title': title,
        'links_menu': links_menu
    }
    return render(request, 'contact.html', context)


def cart(request):
    title = 'Корзина'
    context = {
        'title': title,
        'links_menu': links_menu
    }
    return render(request, 'cart.html', context)

stepshop/stepshop/templates/authapp/_register.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
{{ title|capfirst }}
{% endblock %}

{% block content %}

<h1>{{ title|capfirst }}</h1>

<div class="container">
    <div class="row">
        <div class="mx-auto col-3">
            <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" endtype="multipart/form-data">
                {% csrf_token %}
                {{ register_form.as_p }}
                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

stepshop/stepshop/templates/authapp/edit.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
{{ title|capfirst }}
{% endblock %}

{% block content %}

<h1>{{ title|capfirst }}</h1>

<div class="container">
    <div class="row">
        <div class="mx-auto col-4">

            <div class="user_avatar">
                <img src="/media/{{ user.avatar }}" alt=" {{ user.username }}" class="rounded-circle">
            </div>
            <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ edit_form.as_p }}

                <button type="submit" class="btn btn-primary">Сохранить</button>
                <button class="btn btn-primary">
                    <a href="{% url 'index' %}" class="text-light">На главную</a>
                </button>

                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

stepshop/stepshop/templates/authapp/login.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
{{ title|capfirst }}
{% endblock %}

{% block content %}

<h1>{{ title|capfirst }}</h1>

<div class="container">
    <div class="row">
        <div class="mx-auto col-3">
            <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
                {% csrf_token %}

                {% if next %}
                    <input type="hidden" name="next" value="{{ next }}">
                {% endif %}

                {{ login_form.as_p }}
                <button type="submit" class="btn btn-primary">Войти</button>
            </form>
            <button class="btn btn-round btn-primary">
                <a href="{% url 'auth:register' %}" class="text-light">Зарегистрироваться</a>
            </button>
        </div>
    </div>

</div>
{% endblock %}

stepshop/stepshop/templates/authapp/register.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
{{ title|capfirst }}
{% endblock %}

{% block content %}

<h1>{{ title|capfirst }}</h1>

<div class="container">
    <div class="row">
        <div class="mx-auto col-4">
            <form class="form-horizontal" action="{% url 'auth:register' %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}

                <p>
                    <label for="login">Логин:</label>
                    {{ register_form.username }}
                </p>
                <p>
                    <label for="first_name">Имя:</label>
                    {{ register_form.first_name }}
                </p>
                <p>
                    <label for="password1">Пароль:</label>
                    {{ register_form.password1 }}
                    {{ register_form.errors.password1 }}
                </p>
                <p>
                    <label for="password2">Подтверждение пароля:</label>
                    {{ register_form.password2 }}
                    {{ register_form.errors.password2 }}
                </p>
                <p><label for="email">Email:</label>
                    {{ register_form.email }}
                    {{ register_form.errors.email }}
                </p>
                <p><label for="age">Возраст:</label>
                    {{ register_form.age }}
                    {{ register_form.errors.age }}
                </p>
                <p>{{ register_form.avatar }}</p>

                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}